# Generated by Django 5.2.16 on 2026-07-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_submission_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
